name: 'Create reproductions in an issue'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    description: 'API token for GitHub requests'
    required: true

  label:
    description: 'What label should be on an issue to indicate it has a repro?'
    default: 'has-repro'

  repo:
    description: 'What repo should this action look at, if not set it uses the same repo'

  code-tag:
    description: 'What tag should be applied to the markdown code block?'
    default: 'repro'
    
runs:
  using: 'node12'
  main: 'dist/index.js'
